### ISSUE TITLE
Recommendation 

### ISSUE THREAD

**Issue by efferifick** [Yuvix25/pytov#3]
Hi,

this might not be an issue per se, but looking at the code it seems that regular expressions are used to parse the file contents. Regular expressions are normally hard to debug and might have edge cases which are difficult to find. My recommendation is that you take a look at antlr4. Antrl4 is a parser generator that is very easy to use. Anyhow, if you don't like this issue, feel free to delete it. Otherwise, feel free to look up how to use antlr4. :)

**Comment by Yuvix25** [comment]
I'll take a look at it.
I know the regex is not the right solution for it, I just didn't have any ideas how else to do it.
