### ISSUE TITLE
Does not work for an empty bracket

### ISSUE THREAD

**Issue by andraantariksa** [Yuvix25/pytov#4]
## Step to Reproduce

Create a `test.py`

```
if (1 == 1){}
```

Run

```
pytov test.py
```

## What I got

```
Traceback (most recent call last):

  File test.py, line 1
    if (1 == 1):
               ^
SyntaxError: unexpected EOF while parsing
```

## Expected Result

I expect it will work, maybe by implicitly adds `pass` to the correspond scope

**Comment by Yuvix25** [comment]
You are absolutely right, I'll fix it.
